### ISSUE TITLE
CI test failed with error.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk-wskdeploy#231]
@houshengbo , I submit a pr, but I got a CI test error. please see the log below:
=== RUN   TestTriggerRule
2017/04/06 07:39:31 Warning: Unable to read whisk properties file '/home/travis/.wskprops' (file open error: open /home/travis/.wskprops: no such file or directory)
--- FAIL: TestTriggerRule (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range
goroutine 46 [running]:
panic(0x7bf760, 0xc4200121f0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420094180)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:579 +0x25d
panic(0x7bf760, 0xc4200121f0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/openwhisk/openwhisk-wskdeploy/deployers.createApiEntity(0xc420097580, 0xc42012ada0, 0xc420097590)
	/home/travis/gopath/src/github.com/openwhisk/openwhisk-wskdeploy/deployers/manifestreader.go:275 +0x4ce
github.com/openwhisk/openwhisk-wskdeploy/deployers.(*ManifestReader).SetApis(0xc420055ca0, 0xc420097580, 0xc42008e288, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openwhisk/openwhisk-wskdeploy/deployers/manifestreader.go:251 +0xeb
github.com/openwhisk/openwhisk-wskdeploy/deployers.(*ManifestReader).HandleYaml(0xc420055ca0, 0xc420097580, 0xc42012a7e0, 0xc420103ce0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openwhisk/openwhisk-wskdeploy/deployers/manifestreader.go:85 +0x374
github.com/openwhisk/openwhisk-wskdeploy/deployers.(*ServiceDeployer).ConstructDeploymentPlan(0xc420097580, 0x16, 0xc420097500)
	/home/travis/gopath/src/github.com/openwhisk/openwhisk-wskdeploy/deployers/servicedeployer.go:124 +0x111
github.com/openwhisk/openwhisk-wskdeploy/cmdImp.Deploy(0x0, 0x82443c, 0x1, 0xc420134460, 0x6f, 0xc420097500, 0x71, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openwhisk/openwhisk-wskdeploy/cmdImp/rootImp.go:72 +0x5f8
github.com/openwhisk/openwhisk-wskdeploy/tests/src/integration/triggerrule.TestTriggerRule(0xc420094180)
	/home/travis/gopath/src/github.com/openwhisk/openwhisk-wskdeploy/tests/src/integration/triggerrule/triggerrule_test.go:21 +0x111
testing.tRunner(0xc420094180, 0x85e9c0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:646 +0x2ec
FAIL	github.com/openwhisk/openwhisk-wskdeploy/tests/src/integration/triggerrule	0.017s
?   	github.com/openwhisk/openwhisk-wskdeploy/utils	[no test files]
?   	github.com/openwhisk/openwhisk-wskdeploy/wski18n	[no test files]
make: *** [integration_test] Error 1
The command "make integration_test" exited with 2.
0.01s$ make clean
if [ -f wskdeploy ] ; then rm wskdeploy; fi
Done. Your build exited with 1.

So what might be the issue? can you pls take a look? tks

**Comment by lzbj** [comment]
Perhaps in your test data, there is no api definition, so the parser failed, I need to fix it, not a issue, so close it.
