### ISSUE TITLE
stderr: Debugger not listening on correct location  [::]:5858

### ISSUE THREAD

**Issue by shikhirsingh** [openwhisk/openwhisk-wskdeploy#240]
All I did was install the debugger and run the invoke command. Here is what I got:

`
(wskdb) invoke autoreply-contactus-dev-main
stderr: Debugger listening on [::]:5858

stderr: /private/var/folders/p6/tr59ys4d61jc6_jwtqfv5md40000gn/T/wskdb-36430oM5iuTp5bVRT/autoreply-contactus-dev-main.js-debug:1
(function (exports, require, module, __filename, __dirname) { UEsDBAoAAAAAABEWkUqMIhLlKgMAACoDAAAKAAAAaGFuZGxlci5qc3ZhciBhbnN3ZXIgPSAidGVzdCI7CnZhciB3YXRzb24gPSByZXF1aXJlKCd3YXRzb24tZGV2ZWxvcGVyLWNsb3VkJyk7CgpmdW5jdGlvbiBtYWluKHBhcmFtcykgewoKICAKICB2YXIgbmF0dXJhbF9sYW5ndWFnZV9jbGFzc2lmaWVyID0gd2F0c29uLm5hdHVyYWxfbGFuZ3VhZ2VfY2xhc3NpZmllcih7CiAgICB1c2VybmFtZTogJzY5OGM5NWVjLTg4MDYtNDExMi1iZGNmLTg4M2VhMGYxNmJhZicsCiAgICBwYXNzd29yZDogJ0gzVzFubkxxZWFHbicsCiAgICB2ZXJzaW9uOiAndjEnCiAgfSk7CgogIG5hdHVyYWxfbGFuZ3VhZ2VfY2xhc3NpZmllci5jbGFzc2lmeSh7CiAgICB0ZXh0OiAnSGVsbG8gSSB3YXMgd29uZGVyaW5nIGlmIHlvdSBoYXZlIGEgUmViZWwgRmxhZyB0YWNrIHNldCB0aGF0IHdvdWxkIGZpdCBhIGRyYWZ0IGhvcnNlLicsCiAgICBjbGFzc2lmaWVyX2lkOiAnOTBlN2I0eDE5OS1ubGMtMzgyOTknIH0sCiAgICBmdW5jdGlvbihlcnIsIHJlc3BvbnNlKSB7CiAgICAgIGlmIChlcnIpewogICAgICAgIGNvbnNvbGUubG9nKCdlcnJvcjonLCBlcnIpOwogICAgICAgIGFuc3dlcj1lcnI7CiAgICAgIH0KICAgICAgZWxzZXsKICA
S
stderr: yntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

ok
`
I'm on macOS v10.12.3

**Comment by shikhirsingh** [comment]
wrong location. ooops, posting this in correct repo
